CREATE TABLE MIGRATABELAS (
    TABELA         VARCHAR(200),
    LINHAS         INTEGER,
    PERSONALIZADA  CHAR(1),
    MIGRAR         CHAR(1),
    MIGRADA        CHAR(1)
);


CREATE INDEX MIGRATABELAS_IDX1 ON MIGRATABELAS (TABELA);