SET SERVEROUTPUT ON
BEGIN
FOR I IN
  (SELECT 'ALTER TRIGGER "' || TRIGGER_NAME || '" ENABLE ' AS vSQL, TRIGGER_NAME
     FROM USER_TRIGGERS
     WHERE STATUS = 'DISABLED')
LOOP  
  BEGIN
  EXECUTE IMMEDIATE I.vSQL;  
  DBMS_OUTPUT.PUT_LINE('TRIGGER ATIVADA COM SUCESSO => ' || I.TRIGGER_NAME);
  EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
  END;
END LOOP;
COMMIT;
END;

/*INDICES*/
SET SERVEROUTPUT ON
BEGIN
FOR I IN
  (SELECT 'ALTER TABLE "' || TABLE_NAME || '" ENABLE  CONSTRAINT "' || CONSTRAINT_NAME || '"' AS vSQL,
           CONSTRAINT_NAME
     FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_TYPE = 'R' AND STATUS = 'DISABLED')
LOOP  
  BEGIN
  EXECUTE IMMEDIATE I.vSQL;  
  DBMS_OUTPUT.PUT_LINE('CHAVE ALTERADA COM SUCESSO => ' || I.CONSTRAINT_NAME);
  EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
  END;
END LOOP;
COMMIT;
END;