SELECT GEN_ID(GEN_PROTCTB, 1) FROM RDB$DATABASE

DROP SEQUENCE VIASOFT.GEN_PROTCTB;
CREATE SEQUENCE  VIASOFT.GEN_PROTCTB  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9825 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

DROP SEQUENCE VIASOFT.SEQ_CTBONLINE;
CREATE SEQUENCE  VIASOFT.SEQ_CTBONLINE  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 9825 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;



CREATE SEQUENCE VIASOFT.GEN_CFLAUDO_CODBARRAS INCREMENT BY 1 START WITH 
    1000 MAXVALUE 9999999999999999999999999999 MINVALUE 1000;

CREATE SEQUENCE VIASOFT.GEN_CFLOTECAFE_CODBARRAS INCREMENT BY 1 START WITH 
    1000 MAXVALUE 9999999999999999999999999999 MINVALUE 1000;

CREATE SEQUENCE  VIASOFT.GEN_PNOMECARTAXAS_ID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 38 NOCACHE  NOORDER  NOCYCLE ;


DROP SEQUENCE VIASOFT.GEN_CONTAMOVLAN02_NUMEROCONTRA;
CREATE SEQUENCE VIASOFT.GEN_CONTAMOVLAN02_NUMEROCONTRA INCREMENT BY 1 START WITH 3645  MAXVALUE 9999999999999999999999999999 MINVALUE 1;    


drop sequence GEN_APRVPEDCABHIST_IDAPRVPEDCA; CALL CREATE_SEQUENCE('APRVPEDCABHIST', 'IDAPRVPEDCABHIST');
drop sequence GEN_APRVPEDITEMHIST_IDAPRVPEDI; CALL CREATE_SEQUENCE('APRVPEDITEMHIST', 'IDAPRVPEDITEMHIST');


CREATE SEQUENCE PRIVID_GEN;

DROP SEQUENCE GEN_LUCROMINIMOMARCAITEM_IDLUC; CALL CREATE_SEQUENCE('LUCROMINIMOMARCAITEM', 'IDLUCROMINMARCA');
DROP SEQUENCE GEN_ORDEMPRODMPCUS_IDORDEMPROD; CALL CREATE_SEQUENCE('ORDEMPRODMPCUS', 'IDORDEMPRODMPCUS');
DROP SEQUENCE GEN_SESLABAMOSTRATERC_IDSESLAB; CALL CREATE_SEQUENCE('SESLABAMOSTRATERC', 'IDSESLABAMOSTRATERC');
DROP SEQUENCE GEN_CFGCONTFRETEPROD_CODCFGCON; CALL CREATE_SEQUENCE('CFGCONTFRETEPROD', 'CODCFGCONTFRETEPROD');
DROP SEQUENCE GEN_FORMAPAGTOCOTACAO_IDFORMAP; CALL CREATE_SEQUENCE('FORMAPAGTOCOTACAO', 'IDFORMAPAGTO');
DROP SEQUENCE GEN_FORNECEDORESCOTACAO_IDFORN; CALL CREATE_SEQUENCE('FORNECEDORESCOTACAO', 'IDFORNECEDORES');
DROP SEQUENCE GEN_LUCROMINIMOGRUPOITEM_IDLUC; CALL CREATE_SEQUENCE('LUCROMINIMOGRUPOITEM', 'IDLUCROMINGRUPO');
DROP SEQUENCE GEN_PEDCFGFORMAPARC_IDPEDCFGFO; CALL CREATE_SEQUENCE('PEDCFGFORMAPARC', 'IDPEDCFGFORMAPARC');
DROP SEQUENCE GEN_RECIBOFIXACAOCONF_IDRECIBO; CALL CREATE_SEQUENCE('RECIBOFIXACAOCONF', 'IDRECIBOFIX');
DROP SEQUENCE GEN_SEITEMCALCSEMEADURA_IDITEM; CALL CREATE_SEQUENCE('SEITEMCALCSEMEADURA', 'IDITEMCALCSEMEADURA');
DROP SEQUENCE GEN_SESLABCABTERC_IDSESLABCABT; CALL CREATE_SEQUENCE('SESLABCABTERC', 'IDSESLABCABTERC');
DROP SEQUENCE GEN_SOLCFGFORMAPAGTO_IDSOLCFGF; CALL CREATE_SEQUENCE('SOLCFGFORMAPAGTO', 'IDSOLCFGFORMAPAGTO');
DROP SEQUENCE GEN_COTACAOPEDITEM_IDCOTACAOPE; CALL CREATE_SEQUENCE('COTACAOPEDITEM', 'IDCOTACAOPEDITEM');
DROP SEQUENCE GEN_DESCCOMPOSTO_IDDESCCOMPOST; CALL CREATE_SEQUENCE('DESCCOMPOSTO', 'IDDESCCOMPOSTO');
DROP SEQUENCE GEN_FINALIDADETIPO_FINALIDADEI; CALL CREATE_SEQUENCE('FINALIDADETIPO', 'FINALIDADEID');
DROP SEQUENCE GEN_PARTICIPACAOMINGRUPO_IDPAR; CALL CREATE_SEQUENCE('PARTICIPACAOMINGRUPO', 'IDPARTICIPACAOMINGRUPO');
DROP SEQUENCE GEN_RECIBOFIXACAOITEM_IDRECIBO; CALL CREATE_SEQUENCE('RECIBOFIXACAOITEM', 'IDRECIBOITEM');
DROP SEQUENCE GEN_SELOTEREPRESENT_IDREPRESEN; CALL CREATE_SEQUENCE('SELOTEREPRESENT', 'IDREPRESENT');
DROP SEQUENCE GEN_CLAPARCITEMCAB_CDPARCITEMC; CALL CREATE_SEQUENCE('CLAPARCITEMCAB', 'CDPARCITEMCAB');
DROP SEQUENCE GEN_NFITEMDEVAGROT_IDNFITEMDEV; CALL CREATE_SEQUENCE('NFITEMDEVAGROT', 'IDNFITEMDEVAGROT');
DROP SEQUENCE GEN_PARTICIPACAOMINMARCA_IDPAR; CALL CREATE_SEQUENCE('PARTICIPACAOMINMARCA', 'IDPARTICIPACAOMINMARCA');
DROP SEQUENCE GEN_ROMACFGLOCALEST_IDROMACFGL; CALL CREATE_SEQUENCE('ROMACFGLOCALEST', 'IDROMACFGLOCALEST');
DROP SEQUENCE GEN_CTRCCFGPARCELAMENTO_CTRCPA; CALL CREATE_SEQUENCE('CTRCCFGPARCELAMENTO', 'CTRCPARCID');
DROP SEQUENCE GEN_ITEMCOMPOSCAB_SEQITEMCOMPO; CALL CREATE_SEQUENCE('ITEMCOMPOSCAB', 'SEQITEMCOMPOSCAB');
DROP SEQUENCE GEN_NFCFGVENDELOTEVENC_IDNFCFG; CALL CREATE_SEQUENCE('NFCFGVENDELOTEVENC', 'IDNFCFGVENDELOTEVENC');
DROP SEQUENCE GEN_ORDEMPRODPACUS_IDORDEMPROD; CALL CREATE_SEQUENCE('ORDEMPRODPACUS', 'IDORDEMPRODPACUS');
DROP SEQUENCE GEN_PARTICIPACAOMINTABEL_IDPAR; CALL CREATE_SEQUENCE('PARTICIPACAOMINTABEL', 'IDPARTICIPACAOMINTABEL');
DROP SEQUENCE GEN_ROMACLASSNOME_CLASSIFICACA; CALL CREATE_SEQUENCE('ROMACLASSNOME', 'CLASSIFICACAO');
DROP SEQUENCE GEN_CTRCTARFRETE_IDCTRCTARFRET; CALL CREATE_SEQUENCE('CTRCTARFRETE', 'IDCTRCTARFRETE');
DROP SEQUENCE GEN_VEICULOSCLASS_CLASSIFICACA; CALL CREATE_SEQUENCE('VEICULOSCLASS', 'CLASSIFICACAO');
DROP SEQUENCE GEN_ITENSCOTACAOAPROV_IDITEMCO; CALL CREATE_SEQUENCE('ITENSCOTACAOAPROV', 'IDITEMCOTACAOAPROV');
DROP SEQUENCE GEN_LAYOUTCARTDEP_LAYOUTCARTDE; CALL CREATE_SEQUENCE('LAYOUTCARTDEP', 'LAYOUTCARTDEP');
DROP SEQUENCE GEN_PARTICIPACAOMINITEM_IDPART; CALL CREATE_SEQUENCE('PARTICIPACAOMINITEM', 'IDPARTICIPACAOMINITEM');
DROP SEQUENCE GEN_APRVETAPACFG_IDAPRVETAPACF; CALL CREATE_SEQUENCE('APRVETAPACFG', 'IDAPRVETAPACFG');
DROP SEQUENCE GEN_CONTAMOVLOCALEST_IDCONTAMO; CALL CREATE_SEQUENCE('CONTAMOVLOCALEST', 'IDCONTAMOVLOCALEST');
DROP SEQUENCE GEN_COTACAOCOMPRA_IDCOTACAOCOM; CALL CREATE_SEQUENCE('COTACAOCOMPRA', 'IDCOTACAOCOMPRA');
DROP SEQUENCE GEN_PRETORNOREMESSAREC_IDRETOR; CALL CREATE_SEQUENCE('PRETORNOREMESSAREC', 'IDRETORNO');
DROP SEQUENCE GEN_SOLCFGFORMAPARC_IDSOLCFGFO; CALL CREATE_SEQUENCE('SOLCFGFORMAPARC', 'IDSOLCFGFORMAPARC');
DROP SEQUENCE GEN_ITEMCOMPOSDET_SEQITEMCOMPO; CALL CREATE_SEQUENCE('ITEMCOMPOSDET', 'SEQITEMCOMPOSDET');



CREATE SEQUENCE GEN_WMROTAREALIZADA_ID MINVALUE 1 MAXVALUE 9999999999999999999;
CREATE SEQUENCE GEN_WMTIPOKM_ID MINVALUE 1 MAXVALUE 9999999999999999999999999999;
CREATE SEQUENCE GEN_WMCOLETAMOTIVO_ID MINVALUE 1 MAXVALUE 9999999999999999999999;
CREATE SEQUENCE GEN_WMCACHEMOD_ID;
CREATE SEQUENCE GEN_WMPARAMETROS_ID MINVALUE 1 MAXVALUE 999999999999999999999999;
CREATE SEQUENCE GEN_WMROTAREALIZPESMODULO_ID MINVALUE 1 MAXVALUE 9999999999999;
CREATE SEQUENCE GEN_WMVISITATALHAORECTECNIC_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE GEN_WMVISITATALHAO_ID MINVALUE 1 MAXVALUE 9999999999999999999999;
CREATE SEQUENCE GEN_WMVISITATALHAORECTECNIC_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE GEN_WMVISITA_ID MINVALUE 1 MAXVALUE 9999999999999999999999999999;
CREATE SEQUENCE GEN_WMVISITATALHAO_ID MINVALUE 1 MAXVALUE 9999999999999999999999;
CREATE SEQUENCE GEN_WMROTAREALIZPES_ID MINVALUE 1 MAXVALUE 9999999999999999999;
CREATE SEQUENCE GEN_WMROTAREALIZPESMODULO_ID MINVALUE 1 MAXVALUE 9999999999999;
CREATE SEQUENCE  "VIASOFT"."GEN_WMCOLETARODIZIO_ID" MINVALUE 1 MAXVALUE 9999999;
CREATE SEQUENCE GEN_WMARQUIVO_ID MINVALUE 1 MAXVALUE 999999999999999999999999999;
CREATE SEQUENCE GEN_WMCONTATO_ID MINVALUE 1 MAXVALUE 999999999999999999999999999;
CREATE SEQUENCE GEN_WMROTAGPS_ID INCREMENT BY 1 START WITH 1;